# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.6.0"

require 'yaml'

boxes = YAML.load_file('./boxes.yaml')
common = YAML.load_file('./puppet/hieradata/common.yaml')
puppet_run = (common['orautils_nodemanagerautostart_enabled']) ? "once" : "always"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vbguest.auto_update = false

  config.vm.define "admin" , primary: true do |admin|

    admin.vm.box = boxes['virtualbox']['box']
    admin.vm.box_url = boxes['virtualbox']['box_url']

    admin.vm.provider :vmware_fusion do |v, override|
      override.vm.box = boxes['vmware']['box']
      override.vm.box_url = boxes['vmware']['box_url']
    end

    admin.vm.hostname = "clientlinux.mshome.net"
    admin.vm.synced_folder ".", "/vagrant" #, :mount_options => ["dmode=777","fmode=777"]
    admin.vm.synced_folder "./software", "/software"
	admin.vm.synced_folder "../provision/clientlinux/provision/alfresco_cfg/", "/weblogicfiles"

    #admin.vm.network :private_network, ip: "10.10.10.10", auto_config: false
	admin.vm.network "private_network", ip: "192.168.56.14"
    admin.vm.network "forwarded_port", guest: 7001, host: 7001, guest_ip: "10.0.2.15"
    admin.vm.network "forwarded_port", guest: 7002, host: 7002
    admin.vm.network "forwarded_port", guest: 8011, host: 8011, guest_ip: "123.123.22.21"
    admin.vm.network "forwarded_port", guest: 8011, host: 8012, guest_ip: "123.123.22.22"
    admin.vm.network "forwarded_port", guest: 8021, host: 8021
    admin.vm.network "forwarded_port", guest: 8001, host: 8001
    admin.vm.network "forwarded_port", guest: 18001, host: 18001

    admin.vm.provider :virtualbox do |vb|	
      vb.customize ["modifyvm", :id, "--memory", "3072"]	
      vb.customize ["modifyvm", :id, "--cpus"  , 2]	
    end
    
    admin.vm.provider :vmware_fusion do |vb|
      vb.vmx["numvcpus"] = "2"
      vb.vmx["memsize"] = "3072"
    end	

    admin.vm.provision :shell, path: "./puppet_config.sh"

    # in order to enable this shared folder, execute first the following in the host machine: mkdir log_puppet_weblogic && chmod a+rwx log_puppet_weblogic
    #admin.vm.synced_folder "./log_puppet_weblogic", "/tmp/log_puppet_weblogic", :mount_options => ["dmode=777","fmode=777"]

    admin.vm.provision "puppet", run: puppet_run do |puppet|
      puppet.environment_path     = "puppet/environments"
      puppet.environment          = "development"

      puppet.manifests_path       = "puppet/environments/development/manifests"
      puppet.manifest_file        = "site.pp"

      puppet.options           = [
                                  '--verbose',
                                  '--report',
                                  '--trace',
                                  '--debug',
#                                  '--parser future',
                                  '--strict_variables',
                                  '--hiera_config /vagrant/puppet/hiera.yaml'
                                 ]
      puppet.facter = {
        "environment"     => "development",
        "vm_type"         => "vagrant",
      }

    end
	
	admin.vm.provision :shell, path: "./weblogickrb.sh"

  end
end
