name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: Update packages
        run: |
          brew cask uninstall vagrant
          brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/7f340b97d60907da225e9f5c10e81f9285ef2edb/Casks/vagrant.rb
          brew cask uninstall virtualbox
          brew cask install https://raw.githubusercontent.com/danielmenezesbr/homebrew-cask/virtualbox-6024/Casks/virtualbox.rb
          
      - name: Show packages version
        run: | 
          VBoxManage --version
          vagrant up --version

      - uses: actions/checkout@v2

      - name: WebLogic-Download
        env:
          ORACLE_SSO_USERNAME: ${{ secrets.ORACLE_SSO_USERNAME}}
          ORACLE_SSO_PASSWORD: ${{ secrets.ORACLE_SSO_PASSWORD}}
        run: |
          cd ./puppet-weblogic/software
          pip3 install -r requirements.txt
          python3 download.py
          unzip fmw_12.2.1.3.0_wls_Disk1_1of1.zip
          mv fmw_12.2.1.3.0_wls.jar fmw_12.2.1.2.0_wls.jar

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.vagrant.d/boxes/cdaf-VAGRANTSLASH-WindowsServerDC
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Windows Server DC-Vagrant
        run: |
            vagrant plugin install vagrant-vbguest
            vagrant up dc
            vagrant powershell dc -c 'systeminfo'

      - name: WebLogic-Vagrant
        run: |
          cd ./puppet-weblogic
          vagrant up admin
      
      - name: WebLogic-Test
        run: vagrant provision dc --provision-with weblogic-test
      - run: |
          cd ./puppet-weblogic
          vagrant halt 
          
      - name: Alfresco-Vagrant
        run: vagrant up client
        
      - name: Alfresco-Test
        run: vagrant provision dc --provision-with alfresco-test
