name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1

      - name: always-upload-cache
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: |
            ~/.vagrant.d/boxes/cdaf-VAGRANTSLASH-WindowsServerDC
            /Library/Caches/Homebrew
            ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Update packages
        run: |
          set -exuo pipefail
          brew install virtualbox
          #6.1 - works
          #brew install https://raw.githubusercontent.com/Homebrew/homebrew-cask/aa3c55951fc9d687acce43e5c0338f42c1ddff7b/Casks/virtualbox.rb --cask
          #6.0 - fail
          #brew install https://raw.githubusercontent.com/Homebrew/homebrew-cask/45d768ed9fa4a23cc76fab675cdcd6bf409ab32e/Casks/virtualbox.rb --cask
          #vagrant 2.2.9 works
          #brew install https://raw.githubusercontent.com/danielmenezesbr/alfresco-kerberos/master/.github/workflows/vagrant.rb --cask
          #vagrant last
          brew install vagrant
          curl -L https://raw.githubusercontent.com/Homebrew/homebrew-cask/b6ac3795c1df9f97242481c0817b1165e3e6306a/Casks/react-native-debugger.rb > react-native-debugger.rb && brew install react-native-debugger.rb
          #brew install https://raw.githubusercontent.com/danielmenezesbr/homebrew-cask/virtualbox-6024/Casks/virtualbox.rb --cask
          
      - name: Show packages version
        run: | 
          VBoxManage --version
          vagrant up --version



      - name: Windows Server DC-Vagrant
        run: |
            #/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh restart
            vagrant plugin install vagrant-vbguest
            vagrant up dc --provider=virtualbox
            vagrant powershell dc -c 'systeminfo'

      - name: WebLogic-Vagrant
        env:
          ORACLE_SSO_USERNAME: ${{ secrets.ORACLE_SSO_USERNAME}}
          ORCL_PWD: ${{ secrets.ORACLE_SSO_PASSWORD}}
        run: |
          cd ./puppet-weblogic
          vagrant up admin
      
      - name: WebLogic-Test
        run: vagrant provision dc --provision-with weblogic-test
      - run: |
          cd ./puppet-weblogic
          vagrant halt 
          
      - name: Alfresco-Vagrant
        run: vagrant up client
        
      - name: Alfresco-Test2
        run: vagrant provision dc --provision-with alfresco-test
