name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_1:
    name: WebLogic-Download
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          ORACLE_SSO_USERNAME: ${{ secrets.ORACLE_SSO_USERNAME}}
          ORCL_PWD: ${{ secrets.ORACLE_SSO_PASSWORD}}
        run: |
          wget \
              --no-cookies \
              --no-check-certificate \
              --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
              -O jce_policy-8.zip \
              http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
          wget -O - -q https://raw.githubusercontent.com/typekpb/oradown/master/oradown.sh  | \
          bash -s -- --cookie=accept-weblogicserver-server \
                  --username=$ORACLE_SSO_USERNAME \
          http://download.oracle.com/otn/nt/middleware/12c/12212/fmw_12.2.1.2.0_wls_Disk1_1of1.zip
          wget -O - -q https://raw.githubusercontent.com/typekpb/oradown/master/oradown.sh  | \
          bash -s -- --cookie=accept-weblogicserver-server \
                  --username=$ORACLE_SSO_USERNAME \
          https://download.oracle.com/otn/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
          ls -la
          unzip fmw_12.2.1.3.0_wls_Disk1_1of1.zip

      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: |
            jdk-8u151-linux-x64.tar.gz
            fmw_12.2.1.2.0_wls.jar
            jce_policy-8.zip

  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

#      - name: Setup tmate session
#        env:
#          ORACLE_SSO_USERNAME: ${{ secrets.ORACLE_SSO_USERNAME}}
#          ORCL_PWD: ${{ secrets.ORACLE_SSO_PASSWORD}}
#        uses: mxschmitt/action-tmate@v3

      - name: WebLogic-Download
        env:
          ORACLE_SSO_USERNAME: ${{ secrets.ORACLE_SSO_USERNAME}}
          ORCL_PWD: ${{ secrets.ORACLE_SSO_PASSWORD}}
        run: |
          cd ./puppet-weblogic/software

      - name: Update packages
        run: |
          brew cask uninstall vagrant
          brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/7f340b97d60907da225e9f5c10e81f9285ef2edb/Casks/vagrant.rb
          brew cask uninstall virtualbox
          brew cask install https://raw.githubusercontent.com/danielmenezesbr/homebrew-cask/virtualbox-6024/Casks/virtualbox.rb
          
      - name: Show packages version
        run: | 
          VBoxManage --version
          vagrant up --version

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.vagrant.d/boxes/cdaf-VAGRANTSLASH-WindowsServerDC
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Windows Server DC-Vagrant
        run: |
            vagrant plugin install vagrant-vbguest
            vagrant up dc
            vagrant powershell dc -c 'systeminfo'

      - name: WebLogic-Vagrant
        run: |
          cd ./puppet-weblogic
          vagrant up admin
      
      - name: WebLogic-Test
        run: vagrant provision dc --provision-with weblogic-test
      - run: |
          cd ./puppet-weblogic
          vagrant halt 
          
      - name: Alfresco-Vagrant
        run: vagrant up client
        
      - name: Alfresco-Test
        run: vagrant provision dc --provision-with alfresco-test
