name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Update packages
        run: |
          curl -L https://raw.githubusercontent.com/Homebrew/homebrew-cask/b6ac3795c1df9f97242481c0817b1165e3e6306a/Casks/react-native-debugger.rb > react-native-debugger.rb && brew install react-native-debugger.rb
          brew install https://raw.githubusercontent.com/Homebrew/homebrew-cask/7f340b97d60907da225e9f5c10e81f9285ef2edb/Casks/vagrant.rb --cask
          brew install https://raw.githubusercontent.com/danielmenezesbr/homebrew-cask/virtualbox-6024/Casks/virtualbox.rb --cask
          
      - name: Show packages version
        run: | 
          VBoxManage --version
          vagrant up --version

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.vagrant.d/boxes/cdaf-VAGRANTSLASH-WindowsServerDC
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Windows Server DC-Vagrant
        run: |
            vagrant plugin install vagrant-vbguest
            vagrant up dc
            vagrant powershell dc -c 'systeminfo'

      - name: WebLogic-Vagrant
        env:
          ORACLE_SSO_USERNAME: ${{ secrets.ORACLE_SSO_USERNAME}}
          ORCL_PWD: ${{ secrets.ORACLE_SSO_PASSWORD}}
        run: |
          cd ./puppet-weblogic
          vagrant up admin
      
      - name: WebLogic-Test
        run: vagrant provision dc --provision-with weblogic-test
      - run: |
          cd ./puppet-weblogic
          vagrant halt 
          
      - name: Alfresco-Vagrant
        run: vagrant up client
        
      - name: Alfresco-Test2
        run: vagrant provision dc --provision-with alfresco-test
